### PR TITLE
RM-156376 Release v0.1.1

### PR DESCRIPTION
**Pull request by joecotton-wk**
## Purpose

Adding WK CI so that it builds correctly,

## Solution

High level overview of what was done. This is the roadmap for those who are going to CR.

## Semantic Versioning (check one)

- [ ] The following were changed in a non-backward compatible way and requires a major version bump:
  - _[link to the breaking change in the diff]_
- [ ] Something public was added or changed in backward compatible way, this requires a minor version bump
- [x] No public changes nor new features (backwards-compatible refactor or bug fix), so this can be included in a patch
      release

## How to QA

QA:

- [x] All packages have been renamed from `OneCloudInc` to `Workiva`
- [x] `go build ./...` runs successfully
- [ ] Build passes
- [ ] Skynet passes
- [ ] Aviary passes
- [ ] Rosie runs her checks

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
The items listed below may not capture all security relevant changes. Before providing a security review, be sure to review the entire PR for security impact.
<details>
<summary>(1) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>github.com/gorilla/websocket < 1.4.1</code> via <code>go.sum</code></li>
</details>
<details>
<summary>(1) Security relevant changes were detected</summary>
<li>Watched file <code>aviary.yaml</code> added</li>
</details>

## Action Items
* Request infosec review via Slack: #support-infosec
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=gophoenix">this Splunk dashboard</a> for more CVE details
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by nickmascia-wk — APPROVED** [review]
QA +1

go mod looks correct and build got the deps

**Comment by joecotton-wk** [comment]
QA +1

**Review by edmondoconnell-wk — APPROVED** [review]
QA + 1

**Comment by joecotton-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
